name: Hosted Notebooks Samples Check

on:
  pull_request:
    branches: 
      - feature/samples-gallery
env:
  pipelineVars: '{''qcHash'': ''${{ github.sha }}'', ''githubRepo'': ''${{ github.repository }}'', ''prCommitHash'': ''${{ github.event.pull_request.head.sha }}'', ''isGithubPrBuild'': ''true'' }'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      download_urls: ${{ steps.prepare.outputs.urls }}
    steps:
      - id: prepare
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare varaibles
        run: |
          FILES=$(git diff origin/${{ github.event.pull_request.base.ref }} --name-only)
          FILE_URLS=""
          REGEX='\"download_url\": \"([^\"]*)\"'
          for file in $FILES; do
            echo "Getting download link for $file"
            RESPONSE=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/contents/$file?ref=${{ github.sha }})
            if [[ $RESPONSE =~ $REGEX ]]
            then
              FILE_URLS+="${BASH_REMATCH[1]} "
            fi
          done
          echo "::set-output name=urls::${FILE_URLS}"
  build:
    needs: prepare
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Set status to pending
        run: |
          echo ${{ needs.prepare.outputs.download_urls }}
          curl \
          -X POST \
          -H "Accept: application/json" \
          -u achocron:${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
          -d '{"state":"pending", "description": "Waiting to be run", "context": "Notebook Samples E2E Test"}'
