name: Hosted Notebooks Samples Check

on:
  pull_request:
    branches: 
      - feature/samples-gallery
env:
  pipelineVars: '{''qcHash'': ''${{ github.sha }}'', ''githubRepo'': ''${{ github.repository }}'', ''prCommitHash'': ''${{ github.event.pull_request.head.sha }}'', ''isGithubPrBuild'': ''true'' }'

jobs:
  build:
    name: Print information
    runs-on: ubuntu-latest
    steps:
      - name: Set status to pending
        run: |
          FILES=$(git diff ${{ github.head_ref }} --name-only);
          for file in $FILES; do
            echo $file
