name: Hosted Notebooks Samples Check

on:
  pull_request:
    branches: 
      - feature/samples-gallery
env:
  pipelineVars: '{''qcHash'': ''${{ github.sha }}'', ''githubRepo'': ''${{ github.repository }}'', ''prCommitHash'': ''${{ github.event.pull_request.head.sha }}'', ''isGithubPrBuild'': ''true'' }'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print information
        run: |
          git branch
          FILES=$(git diff origin/${{ github.event.pull_request.base.ref }} --name-only)
          for file in $FILES; do
            echo $file
          done
          
